name: Hello Actions

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      - name: Say hello
        run: echo "Hello from GitHub Actions ${{ vars.JENKINS_URL }}"
      - name: Ping Jenkins
        run: curl https://subjective-font-search-frame.trycloudflare.com
